### PR TITLE
Added Parallelization on ClassLevel on all tests 

### PR DESCRIPTION
**Pull request by HeroMaxPower**
## Description
Adds AssemblyInfo.cs to all test projects.

Changes the execution of n processors and executes tests on a thread at class level via 
`[assembly: Parallelize(Workers = 0, Scope = ExecutionScope.ClassLevel)]`

Should improve test execution times. Hopefully without breaking tests.

## Related issue
Implements #2332

### CODE REVIEW

**Comment by nohwnd** [comment]
The parallelized builds take 2h, while most of the other passing builds take 30 minutes. 2h looks like a timeout. Are you hitting deadlocks? I would like to avoid deadlocks, even occasional.

**Comment by HeroMaxPower** [comment]
> The parallelized builds take 2h, while most of the other passing builds take 30 minutes. 2h looks like a timeout. Are you hitting deadlocks? I would like to avoid deadlocks, even occasional.

Not sure what im hitting at the moment the infamous 'it works on my box' applies here. I could approach it from a different angle. I could create a PR and then add the parallelism each commit and if one fails revert and move onto the next project.

**Comment by HeroMaxPower** [comment]
Ok i did it! shaves off 5 mins on the build was it worth it 👍. so good news is if you want to bump up your cores on your AzureDevOps agent you will reap further benefits.

**Comment by nohwnd** [comment]
Let's run it few more times to see that you were not just lucky this time. 🙂 

I'll think about merging this. Looking at the errors in the failures it seems like a bit of guesswork to know what happened, some are obvious (locked files), but some are not. 5 minutes per run is nice but not extremely significant, I don't usually sit around and wait for the tests to finish, and if they fail once out of 5 times because of parallelization issues I am still better off running them in sequence.

**Comment by nohwnd** [comment]
@HeroMaxPower  😁 yikes, a timeout...

**Comment by HeroMaxPower** [comment]
Request Rebuild X4

**Comment by nohwnd** [comment]
@HeroMaxPower Max thanks for undertaking this, but please give up now. The results are pretty unstable and I can't responsibly merge that. :)

**Comment by HeroMaxPower** [comment]
> @HeroMaxPower Max thanks for undertaking this, but please give up now. The results are pretty unstable and I can't responsibly merge that. :)

Sure no problem, was fun though! 👍

**Pull request closed without merging**
