### PR TITLE
Onboard repository to arcade

### LINKED ISSUE #3846: Update projects to build net7.0 TFM
Source build requires projects to build with the current TFM or a supported netstandard TFM. vstest currently targets net6.0. Ideally this would be updated to net7.0. If that is not possible, the TFM could be conditioned for source-build but ideally the regular and source build would be identical.

cc @Haplois 

[AB#1568715](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1568715)

### LINKED ISSUE #4068: Spurious warnings on Linux source-build
## Description
The VSTest source-build on Linux produces some errors that do not affect the build but can still confuse users.

## Steps to reproduce
clone https://github.com/dotnet/installer
./build.sh /p:ArcadeBuildTarball=true /p:TarballDir=/path/to/tarball
cd /path/to/tarball
./prep.sh
./build.sh
check artifacts/logs/vstest.log

## Expected behavior
There should be no warnings or errors that do not affect the build.  These appear to all be related to Windows or other files that do not exist in source-build.

## Actual behavior
A couple different types of errors:
```cp: cannot stat '/<<PKGBUILDDIR>>/src/vstest/artifacts/source-build/self/package-cache/[microsoft.visualstudio.coverage.io/17.0.0-beta.21471.1/lib/netstandard2.0/**': No such file or directory```
```cp: cannot stat '/<<PKGBUILDDIR>>/src/vstest/artifacts/source-build/self/package-cache/system.diagnostics.eventlog/7.0.0-rtm.22507.1/runtimes/win/**': No such file or directory```

Seen on Ubuntu 22.04 by a customer and RHEL8 by me.

### LINKED ISSUE #4256: vstest Maestro publishing fails to push MergedManifest.xml correctly
## Description

Vstest builds do not download correctly for .NET's release infrastructure. https://dev.azure.com/dnceng/internal/_build/results?buildId=2086434&view=logs&j=40e1e683-ea82-5be9-b25e-899b65e1c0cb&t=6e491791-6ce2-572a-3132-c49a3995e637&l=1861

```
Downloading asset assets/manifests/microsoft-vstest/17.5.0-ci/MergedManifest.xml
    Failed to download asset, errors shown below:
```

The version number here is wrong (should be the non-stable version number of vstest. Please work with dnceng FR to resolve.

### LINKED ISSUE #4305: Localization is disabled in Linux builds
## Description

There is an issue with localization in Linux builds - the following property would be initialized to `false`: https://github.com/microsoft/vstest/blob/4cf1986ee6f2c7ec42efdbbda84d16a0435f741b/scripts/build.sh#L149

It seems that specifying `-noloc` would turn on localization, which is the opposite of the switch intent.

On Windows builds, this is working fine as the code is correct: https://github.com/microsoft/vstest/blob/4cf1986ee6f2c7ec42efdbbda84d16a0435f741b/scripts/build.ps1#L97

This affects production of localized vstest binaries in source-build - on Linux machines.

## Steps to reproduce

Run the build on linux machines - do not specify `-noloc`.

## Expected behavior

Localized binaries are produced and packaged together with neutral binaries.

## Actual behavior

No localized binaries are produced.

## Environment

This repros in regular Linux builds, but also in source-build.

### LINKED ISSUE #4311: Update net7.0 TFM references to net8.0
In order to be source-build compliant for the .NET 8.0 release.  All projects targeting a `net7.0` TFM must be upgraded to `net8.0`.  It is preferred that a new [`NetCurrent` Arcade property](https://github.com/dotnet/arcade/pull/12161) be utilized as it eliminates this type of maintenance work for every release.

### PR DESCRIPTION
**Pull request by Evangelink**
## Description

Onboard repository to arcade.

## Related issue

- Fixes #4311 by using `NetCurrent` property for source build builds.
- Fixes #4305 by having no special exclusion of localizations
- I think it should fix #4256 (@mmitche how could we verify?)
- Fixes #4068
- Fixes #3846

### CODE REVIEW

**Comment by Evangelink** [comment]
You can use https://dnceng.visualstudio.com/internal/_build/results?buildId=2124009

**Comment by mmitche** [comment]
That's looking pretty good!

**Comment by MarcoRossignoli** [comment]
@nohwnd can we abandon this one?

**Comment by nohwnd** [comment]
I've merged into mirror and pushed here (not ideal, but happened), the code is in main (including amaurys commits), and this PR is redundant. The linked issues are closed with link to the merge commit: https://github.com/microsoft/vstest/commit/d18720133f78f78142c87468275ee0694673a4cd

**Pull request closed without merging**
