### PR TITLE
Patch integration and add source-build leg to PR validation

### LINKED ISSUE #2929: ArPow stage 2: implementing source-build CI
To make sure ArPow (arcade-powered source-build) keeps working in this repo, we need to add it to PR validation. We also need it to run in the official build to publish source-built artifacts that can be tested downstream.

See <https://github.com/dotnet/source-build/blob/master/Documentation/planning/arcade-powered-source-build/onboarding/ci-onboarding.md> for ArPow CI onboarding info.

Let us know when an official build runs with ArPow enabled, and the source-build team will look at it to greenlight the artifacts or make fixes.

See the [ArPow implementation](https://github.com/dotnet/source-build/blob/master/Documentation/planning/arcade-powered-source-build/implementation-plan.md) for additional details.

### LINKED ISSUE #2930: ArPow followup: incorporate the .patch files added to the repo
The infra enabling ArPow (arcade-powered source-build) involves some `.patch` files checked into this repo at `eng/source-build-patches/*.patch` that fix up the repo to work for source-build. These patch files are prone to conflicting with dev changes, and may block some PRs until the PR author fixes up the patch file to match. The changes in these `.patch` files should be incorporated into the main branch of this repo to remove this possibility.

Some background on source-build patches, for anyone who isn't familiar with previous pushes for patch incorporation:

A patch is essentially just a commit that has been extracted from Git into a `.patch` file that can be applied on demand. The effort to build .NET from source involves creating patches because repos make changes that are incompatible with source-build and need to be fixed up after the original released source code has already been finalized. When the original repo gets PRs over time for servicing, the PR changes sometimes conflict with the source-build patches, just like a merge conflict. The patch files need to be fixed up when this happens, which is a significant maintenance problem for the source-build team.

Several times, the source-build team has pushed for "patch incorporation". This means to merge the commit represented in the `.patch` file into the original repo's official branch. Doing so prevents patch merge conflicts, because there's no longer a patch to merge against. However, patches inevitably pile up again when getting subsequent servicing releases to work in source-build.

ArPow lets us end this maintenance-heavy process. By running source-build inside CI, patch merge conflicts will immediately block PR validation, so fixup can be handled in place, not solely by the source-build team. Running source-build in CI also means creating new patches won't be necessary except in exceptional circumstances.

This issue tracks using `git am eng/source-build-patches/*.patch` and submitting a PR to incorporate the patches, or making changes to the repo that accomplish the same goals as the patches.

See the [ArPow implementation](https://github.com/dotnet/source-build/blob/master/Documentation/planning/arcade-powered-source-build/implementation-plan.md) for additional details.

### PR DESCRIPTION
**Pull request by MichaelSimons**
- Fixes #2929 
 - Fixes #2930

### CODE REVIEW

**Comment by Haplois** [comment]
@MichaelSimons, thanks for the help. I’ll look at this today.

**Comment by MichaelSimons** [comment]
@Haplois, I discovered there was a 5.0 patch that was missing which I have integrated.  The PR is now green.

There are two main pieces remaining that can be included or checked in later according to your preference.

1. Add source-build leg to the internal CI build.  The source build intermediate package produced needs to get published to BAR.
2. Complete integrating the two remaining patches.

**Comment by Haplois** [comment]
@MichaelSimons, sourcebuild works well -- and I integrated most of the patches. (There is only one now.) I was verifying the output, and it doesn't look correct. `Microsoft.TestPlatform.CLI` is wrong, and missing files. I don't know `.sh` scrips, I'll need to fix the generation for those files.

We also generate a lot more packages. Does source build only need those two?

**Comment by MichaelSimons** [comment]
> We also generate a lot more packages. Does source build only need those two?
These are the only two that we build in .NET 5.0 source-build.

**Comment by Haplois** [comment]
Fixed the `.Build` package, and fixing `.CLI` package. Will merge in the morning and update our pipeline.

**Comment by Haplois** [comment]
@MichaelSimons, I minimized most of the patches. There is only one left now; we can fix it too - but it will be a waste of time since we plan to change move our package generation to arcade. With that change I'll remove these patches. I think I fixed all tests etc, I'll merge this after a successful build.

**Comment by MichaelSimons** [comment]
Thanks for working on this @Haplois.  I agree it would be wasteful to integrate the patch given your plans to move package generation to arcade.

**Review by Haplois — APPROVED** [review]

**Pull request merged**
