### PR TITLE
Get Latest extensions from vsualm

### PR DESCRIPTION
**Pull request by smadala**
- fixes for cpp folder name
- Latest TMI adapter for NAR results fix

### CODE REVIEW

**Review by mayankbansal018 — APPROVED** [review]
Since we are picking from vsualm, & binaries are not signed there, please do make sure that in our external package, what all binaries we are bringing, are at least added in verify signing steps, & that we do verify we check if native dll's are signed as well

**Comment by harshjain2** [comment]
@dotnet-bot test this please.

**Comment by codito** [comment]
@smadala does this fix https://github.com/Microsoft/vstest/issues/1214?

**Review by codito — APPROVED** [review]

**Comment by smadala** [comment]
@codito CPP directory path reduce 13 character, this folder was blocking cloudbuild tpv2 packages to restore on dev machine and try out tpv2 with qtest on local dev machine.

**Pull request merged**
