### PR TITLE
Bumped TP version to 17.7.0 (#4346)Co-authored-by: Codrin Poienaru <copoiena@microsoft.com> Co-authored-by: Jakub Jareš <me@jakubjares.com>

### PR DESCRIPTION
**Pull request by cvpoienaru**
Bumped TP version to 17.7.0.

### CODE REVIEW

**Review by MarcoRossignoli — APPROVED** [review]

**Comment by MarcoRossignoli** [comment]
@cvpoienaru can you solve and merge this one?

**Comment by MarcoRossignoli** [comment]
@nohwnd is it fine to you?

**Comment by nohwnd** [comment]
Merged, main. Fixed versions in the new locations. Packages in the pipeline had the correct branding. So I force merged.

**Pull request merged**
