### PR TITLE
Update Fakes packages

### PR DESCRIPTION
**Pull request by vritant24**
## Description
Update Fakes package for the following changes:
1. Add Arm support
2. Fix issues in V2 for .exe files.

### CODE REVIEW

**Review by AbhitejJohn — APPROVED** [review]

**Comment by Evangelink** [comment]
I have relaunched CI steps to see if tests are flaky or if PR is impacting some tests.

**Comment by vritant24** [comment]
@Evangelink @AbhitejJohn 
I've tested this locally, I think it should be good to merge

**Review by Evangelink — APPROVED** [review]

**Comment by Evangelink** [comment]
@AbhitejJohn @vritant24 Is 17.4 preview 2 enough?

**Comment by AbhitejJohn** [comment]
@Evangelink : yup, that should be good.

**Pull request merged**
