### PR TITLE
Use bitness from process or OS

### LINKED ISSUE #13157: With NET 5 RC1 x86 SDK installed on x64 OS, run Unit test failed with error: Testhost process exited with error: A fatal error occurred, the required library hostfxr.dll could not be found...
Machine OS: win10-x64
**Repro Steps**
Install NET 5 RC1 x86 SDK from https://github.com/dotnet/installer on x64 OS
dotnet new xunint/mstest/nunit in CLI
dotnet build and then dotnet test

**Expected result:**
Unit test run successfully

**Actual result:**
run failed with below error:
image
Testhost process exited with error: A fatal error occurred, the required library hostfxr.dll could not be found.
If this is a self-contained application, that library should exist in [C:\Users\v-danche\today\hahah\bin\Debug\net5.0\].
If this is a framework-dependent application, install the runtime in the default location [C:\Program Files\dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location.
. Please check the diagnostic logs for more information.

Test Run Aborted.
C:\Program Files (x86)\dotnet\sdk\5.0.100-rc.1.20427.1\Microsoft.TestPlatform.targets(32,5): error MSB4181: The "Microsoft.TestPlatform.Build.Tasks.VSTestTask" task returned false but did not log an error. [C:\Users\v-danche\today\hahah\hahah.csproj]

**Note:
It doesn't repro on x64 SDK.**
It only repro on NET 5 RC1 x86.

Dotnet --info:
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.1.20427.1
 Commit:    dd2e854c91

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   C:\Program Files (x86)\dotnet\sdk\5.0.100-rc.1.20427.1\

Host (useful for support):
  Version: 5.0.0-rc.1.20426.10
  Commit:  bfc00e4e13

.NET SDKs installed:
  5.0.100-rc.1.20427.1 [C:\Program Files (x86)\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0-rc.1.20426.3 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20426.10 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.1.20426.4 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

### PR DESCRIPTION
**Pull request by nohwnd**
## Description
Based on where we are running from, choose the bitness for dotnet SDK either from the OS or from the process. On 64-bit OS when we run from .NET Framework console we want to find 64-bit dotnet SDK, but when running from 32-bit dotnet we want to prefer 32-bit SDK. 

## Related issue
Fix https://github.com/dotnet/sdk/issues/13157

### CODE REVIEW

**Review by cvpoienaru — APPROVED** [review]

**Review by Sanan07 — APPROVED** [review]

**Comment by nohwnd** [comment]
@tannergooding  in case you want to have a look.

**Comment by tannergooding** [comment]
👍. Should there also be an explicit switch (probably) tracked via a separate issue/PR) to allow specifying the target architecture so devs can force running 32-bit tests from the 64-bit SDK or vice-versa?

**Review by Haplois — APPROVED** [review]

**Comment by tannergooding** [comment]
@nohwnd, I can log an issue suggesting the above. Should it be logged here in `microsoft/vstest` or against `dotnet/sdk`?

**Comment by nohwnd** [comment]
> @nohwnd, I can log an issue suggesting the above. Should it be logged here in `microsoft/vstest` or against `dotnet/sdk`?

make it vstest please, we will do the work here and in dotnet/sdk if needed as well.

**Comment by tannergooding** [comment]
I logged https://github.com/microsoft/vstest/issues/2576

**Pull request merged**
