### PR TITLE
Resolves: Add native GitHub continuous code security and quality analysis

### LINKED ISSUE #3010: Add native GitHub continuous code security and quality analysis
- [CodeQL](https://github.com/github/codeql) is an open source code scanning tool for discovering vulnerabilities across a codebase

Pipeline Foundation is **a non-profit initiative** with the sole purpose of giving back to the IT community by assisting OSS projects with DevOps implementations and best practices.

Built with ❤ by [Pipeline Foundation](https://pipeline.foundation).

### PR DESCRIPTION
**Pull request by aleks-ivanov**
- add `codeql-analysis.yml` which automatically enables CodeQL code security and quality scanner. It executes on every push commit, PR, manually and every day at 8:00AM UTC. A scan check can be viewed on commits and PRs. All alerts and fix suggestion can be viewed at **Security** tab -> **Code scanning alerts** -> **CodeQL**

Resolves #3010

### CODE REVIEW

**Comment by aleks-ivanov** [comment]
> @aleks-ivanov It seems that the PR is not working as-is (there are issues with building). Is it something you would be willing to fix?

Hi @Evangelink. Yes absolutely, we will look into it asap.

**Comment by Evangelink** [comment]
@aleks-ivanov No rush but I am curious if you have any idea when you will be able to do the extra steps?

**Comment by aleks-ivanov** [comment]
> @aleks-ivanov No rush but I am curious if you have any idea when you will be able to do the extra steps?

Hi, I just tested the CodeQL workflow as is and it seems to work properly.

Here is the log of the run -> https://github.com/aleks-ivanov/vstest/actions/runs/2514480345

The build runs without a hitch and then the CodeQL scanning analysis is compiled successfully as well.

**Comment by Evangelink** [comment]
@aleks-ivanov Thanks, I will try to have a look and merge this asap if all is good :)

**Comment by aleks-ivanov** [comment]
> @aleks-ivanov Thanks, I will try to have a look and merge this asap if all is good :)

I am currently running a test with the new version of the CodeQL action, so if everything goes well, I will update the PR.

**Comment by aleks-ivanov** [comment]
@Evangelink I updated the CodeQL actions suite and the workflow runs properly without any issues. Apologies for the delay!

**Comment by Evangelink** [comment]
Hi @aleks-ivanov! I have just learn that our infra teams have enabled codeql on our AzDo builds. We will sync with them and will probably enable some analysis on the public builds too. 

Based on that I will have to close this PR. We are sorry to have made you work for nothing but we really appreciate your contribution and commitment to improve quality.

Have a lovely day!

**Pull request closed without merging**
