### PR TITLE
ArPow stage 1: local source-build infrastructure

### LINKED ISSUE #2076: [ArPow] Onboard vstest to arcade-powered source-build

### PR DESCRIPTION
**Pull request by MichaelSimons**
This PR adds the local build infrastructure that lets ArPow (arcade-powered source-build) run in this repo. See <https://github.com/dotnet/source-build/blob/master/Documentation/planning/arcade-powered-source-build/onboarding/local-onboarding.md> for more details about how it works.

To try it out locally, run this on Linux: `./eng/common/build.sh -c Release --restore --build --pack /p:ArcadeBuildFromSource=true -bl`

The `.patch` files being introduced are the current [patches required to source-build in 5.0](https://github.com/dotnet/source-build/tree/release/5.0/patches/vstest).

This PR should have no effect on ordinary builds, or CI. During ArPow stage 2, the repo team will be asked add source-build to CI: PR validation and official builds.  Additionally repo teams will examine and integrate the `.patch` files into the repo.

For <https://github.com/dotnet/source-build/blob/master/Documentation/planning/arcade-powered-source-build/implementation-plan.md>

Fixes: https://github.com/dotnet/source-build/issues/2076.

### CODE REVIEW

**Comment by MichaelSimons** [comment]
cc @dseefeld, @crummel - please review.

**Comment by Haplois** [comment]
`./eng/common/build.sh -c Release --restore --build --pack /p:ArcadeBuildFromSource=true -bl` works, but we have build failures.

**Comment by MichaelSimons** [comment]
>./eng/common/build.sh -c Release --restore --build --pack /p:ArcadeBuildFromSource=true -bl works, but we have build failures.

Can you please point me to which build failures you are referring to?

**Comment by Haplois** [comment]
I shared my `.binlog` file privately with you. Those errors are most probably because that we don't support arcade build scripts yet.

**Review by Haplois — APPROVED** [review]

**Comment by MichaelSimons** [comment]
Looking at the `.binlog`, an older version of `.dotnet` and `arcade` are getting picked-up which don't match what is specified in the `global.json` and `Versions.Details.xml` files.  Try cleaning your build environment and running another build.

**Comment by Haplois** [comment]
It's a completely new WSL environment. I'll try again thou.

**Pull request merged**
