### PR TITLE
Enable default compile items for Microsoft.TestPlatform.PlatformAbstractions

### PR DESCRIPTION
**Pull request by sharwell**
This change allows all files to show in Solution Explorer, with the content conditionally included according to well-known compile-time definitions.

### CODE REVIEW

**Comment by nohwnd** [comment]
I always wondered why they did it this way, instead of the way you propose in this PR. But it never got high enough on my todo list, because it works. Will merge this in few days once we finalize some other changes. Thank you!

**Comment by Haplois** [comment]
I already did most of this work for my work on adding support for netstandard1.0 to our primitives. @nohwnd, please don't merge until I compare it with mine.

**Comment by nohwnd** [comment]
@Haplois it's yours now. @sharwell  needs this merged for #2554, but let's merge tomorrow at earliest.

**Review by Haplois — APPROVED** [review]

**Review by Haplois — CHANGES_REQUESTED** [review]
I am doing some tests, will merge soon.

**Review by Haplois — APPROVED** [review]

**Pull request merged**
