### PR TITLE
Replacing calls to BuildMultipleAssemblyPath when passing only one source in acceptance tests

### LINKED ISSUE #3510: Consider replacing calls to BuildMultipleAssemblyPath when passing only one source
There is no need to use `BuildMultipleAssemblyPath` if we pass only one source, instead we could use `GetASsetFullPath`.

_Originally posted by @Evangelink in https://github.com/microsoft/vstest/pull/3459#discussion_r832439372_

### PR DESCRIPTION
**Pull request by daveMueller**
## Description
Replacing calls to BuildMultipleAssemblyPath by GetASsetFullPath when passing only one source

## Related issue
fixes #3510

### CODE REVIEW

**Comment by daveMueller** [comment]
> @microsoft-github-policy-service agree

**Review by MarcoRossignoli — APPROVED** [review]
@nohwnd looks good to me, wdyt?

**Comment by daveMueller** [comment]
It seems one test is failing with my change. I'll check this once I find some time in the next days.

**Comment by nohwnd** [comment]
Looks good, will have to merge main after migration to Arcade (dotnet build infrastructure) is done.

**Pull request merged**
