### PR TITLE
Fix Collect Code coverage with no runsettings

### PR DESCRIPTION
**Pull request by smadala**
**Issue:**
NRE when running code coverage with no runsettings .

```PS
PS C:\Users\samadala\src\vstest> C:\Users\samadala\src\vstest\tools\dotnet\dotnet.exe "C:\Users\samadala\src\vstest\artifacts\Debug\netcoreapp2.0\vstest.console.dll" "C:\Users\samadala\src\vstest\test\TestAssets\SimpleTestProject\bin\Debug\netcoreapp1.1\SimpleTestProject.dll" --collect:"Code coverage" /testadapterpath:C:\Users\samadala\src\vstest\src\DataCollectors\TraceDataCollector\bin\Debug\netstandard2.0
Microsoft (R) Test Execution Command Line Tool Version 15.8.0-dev
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Data collector 'Code Coverage' message: Failed to initialize code coverage datacollector with error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Coverage.DynamicCoverageDataCollectorImpl.PrepareVanguardProcess(XmlElement configurationElement) in C:\Users\samadala\src\vstest\src\DataCollectors\TraceDataCollector\VanguardCollector\DynamicCoverageDataCollectorImpl.cs:line 266
   at Microsoft.VisualStudio.Coverage.DynamicCoverageDataCollectorImpl.Initialize(XmlElement configurationElement, IDataCollectionSink dataSink, IDataCollectionLogger logger) in C:\Users\samadala\src\vstest\src\DataCollectors\TraceDataCollector\VanguardCollector\DynamicCoverageDataCollectorImpl.cs:line 137
   at Microsoft.VisualStudio.Coverage.DynamicCoverageDataCollector.OnInitialize(XmlElement configurationElement) in C:\Users\samadala\src\vstest\src\DataCollectors\TraceDataCollector\VanguardCollector\DynamicCoverageDataCollector.cs:line 63.
Data collector 'Code Coverage' message: Data collector 'Code Coverage' threw an exception during type loading, construction, or initialization: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Coverage.DynamicCoverageDataCollectorImpl.PrepareVanguardProcess(XmlElement configurationElement) in C:\Users\samadala\src\vstest\src\DataCollectors\TraceDataCollector\VanguardCollector\DynamicCoverageDataCollectorImpl.cs:line 266
   at Microsoft.VisualStudio.Coverage.DynamicCoverageDataCollectorImpl.Initialize(XmlElement configurationElement, IDataCollectionSink dataSink, IDataCollectionLogger logger) in C:\Users\samadala\src\vstest\src\DataCollectors\TraceDataCollector\VanguardCollector\DynamicCoverageDataCollectorImpl.cs:line 137
   at Microsoft.VisualStudio.Coverage.DynamicCoverageDataCollector.OnInitialize(XmlElement configurationElement) in C:\Users\samadala\src\vstest\src\DataCollectors\TraceDataCollector\VanguardCollector\DynamicCoverageDataCollector.cs:line 71

   at Microsoft.VisualStudio.TraceCollector.BaseDataCollector.Initialize(XmlElement configurationElement, IDataCollectionEvents events, IDataCollectionSink dataSink, IDataCollectionLogger logger, IDataCollectionAgentContext agentContext) in C:\Users\samadala\src\vstest\src\DataCollectors\TraceDataCollector\BaseDataCollector.cs:line 68
   at Microsoft.VisualStudio.TraceCollector.BaseDataCollector.Initialize(XmlElement configurationElement, DataCollectionEvents events, DataCollectionSink dataSink, DataCollectionLogger logger, DataCollectionEnvironmentContext environmentContext) in C:\Users\samadala\src\vstest\src\DataCollectors\TraceDataCollector\BaseDataCollector.cs:line 37
   at Microsoft.VisualStudio.TestPlatform.Common.DataCollector.DataCollectorInformation.InitializeDataCollector() in C:\Users\samadala\src\vstest\src\Microsoft.TestPlatform.Common\DataCollection\DataCollectorInformation.cs:line 117
   at Microsoft.VisualStudio.TestPlatform.Common.DataCollector.DataCollectionManager.LoadAndInitialize(DataCollectorSettings dataCollectorSettings, String settingsXml) in C:\Users\samadala\src\vstest\src\Microsoft.TestPlatform.Common\DataCollection\DataCollectionManager.cs:line 471..
Failed   FailingTest
Error Message:
 Assert.AreEqual failed. Expected:<2>. Actual:<3>.
Stack Trace:
   at SampleUnitTestProject.UnitTest1.FailingTest() in C:\Users\samadala\src\vstest\test\TestAssets\SimpleTestProject\UnitTest1.cs:line 39
```

**Root cause**
Trace DataCollector receiving `<Configuration><Framework>.NETCoreApp,Version=v1.1</Framework></Configuration>` which doesn't have code coverage configuration.

**Fix**
If there no code coverage config, pass default configuration.

### CODE REVIEW

**Review by mayankbansal018 — APPROVED** [review]
:shipit:

**Comment by smadala** [comment]
@dotnet-bot Please test this.

**Comment by smadala** [comment]
@dotnet-bot Please test this

**Comment by smadala** [comment]
@dotnet-bot test

**Comment by smadala** [comment]
@dotnet-bot test this

**Comment by smadala** [comment]
@dotnet-bot test this please

**Comment by smadala** [comment]
@dotnet-bot test this please

**Pull request merged**
