### PR TITLE
Convert to auto property

### LINKED ISSUE #10364: [9.0] Source-build issue in stage 2 build
Originally created in source-build repo: https://github.com/dotnet/source-build/issues/4641

Stage 2 build is failing in `vstest` with the following error:

```
    /vmr/src/vstest/src/Microsoft.TestPlatform.PlatformAbstractions/common/Tracing/PlatformEqtTrace.cs(87,5): error IDE0032: Use auto property (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0032) [/vmr/src/vstest/src/Microsoft.TestPlatform.PlatformAbstractions/Microsoft.TestPlatform.PlatformAbstractions.csproj::TargetFramework=net9.0]
```

Test build (internal link): https://dev.azure.com/dnceng/internal/_build/results?buildId=2550295&view=logs&j=3121c41d-6088-53a5-4ef6-9a86f3460fe9&t=334539f4-dcef-5cad-a240-02997b3146e7

This can be reproduced in `vstest` repo builds by updating SDK to the latest 9.0 build.

cc @nohwnd

### PR DESCRIPTION
**Pull request by nohwnd**
## Description

Fix #10364

### CODE REVIEW

**Comment by NikolaMilosavljevic** [comment]
There's another of this type of issues: https://github.com/microsoft/vstest/issues/10364#issuecomment-2389914170

I'm not sure why build is not reporting all issues at once.

**Comment by nohwnd** [comment]
Fixing it in the analyzer suggested way causes more problems than it solves, I am downgrading the severity of to suggestion.

**Comment by NikolaMilosavljevic** [comment]
@nohwnd this is needed in .NET 9.0 release (vstest 17.12). Is there a backport PR to `rel/17.12` branch?

**Comment by nohwnd** [comment]
I just cherry picked into rel/17.12.

**Pull request merged**
