### PR TITLE
Add Microsoft.Extensions.DependencyModel dependency to test host nuspec

### LINKED ISSUE #393: Build warning on build of default xunit template (netcore)
## Description
Building the default xunit test project shows an warning on dependency resolution conflict.

Reported by José Manuel Nieto Sánchez in [developer community](https://developercommunity.visualstudio.com/content/problem/15159/xunit-test-project-net-core-found-conflicts-betwee.html)

## Steps to reproduce
1. Create a new xunit test project (netcore)
2. Build the project

## Expected behavior
Build succeeds without warning.

## Actual behavior
Build succeeds with warning.
```
Build started, please wait...
C:\Program Files\dotnet\sdk\1.0.0-rc3-004530\Microsoft.Common.CurrentVersion.targets(1912,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [C:\temp\test\test.csproj]
Build completed.

Test run for C:\temp\test\bin\Debug\netcoreapp1.0\test.dll(.NETCoreApp,Version=v1.0)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Passed   Tests.UnitTest1.Test1

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 1,7098 Seconds
```

## Environment
Microsoft.NET.Test.Sdk: `15.0.0-preview-20170125-04`

### PR DESCRIPTION
**Pull request by smadala**
Fixes #393.
Should be merged after [xUnit PlatformAbstraction fix](https://github.com/xunit/visualstudio.xunit/pull/96) release because DependencyModel 1.1 will break xUnit with error 
```System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DotNet.InternalAbstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60```.

Related issues: xunit/xunit#1080, xunit/xunit#1088

/cc @srivatsn @sbaid

### CODE REVIEW

**Comment by smadala** [comment]
@onovotny Can you please provide tentative date for visualstudio.xunit 2.2-beta6 release?

**Comment by codito** [comment]
We need to take this for rtw.

@Faizan2304 this change requires the following as well?
* CrossPlatEngine refers DependencyModel 1.1.0 in 15.0-rtm branch
* Dotnet-CLI repo builds with DependencyModel 1.1.0

/cc @livarcocc

**Comment by davidfowl** [comment]
Is this already fixed? When is it going in?

**Comment by onovotny** [comment]
@davidfowl xunit beta6/RC has this fix already. The latest MyGet feed has it. I believe @bradwilson is publishing a quick RC any day now followed by the stable 2.2 ver.

**Comment by Faizan2304** [comment]
> @Faizan2304 this change requires the following as well?
CrossPlatEngine refers DependencyModel 1.1.0 in 15.0-rtm branch
Dotnet-CLI repo builds with DependencyModel 1.1.0

> 
Yes we should but some how its working without second point ``Dotnet-CLI repo builds with DependencyModel 1.1.0``

**Pull request merged**
