### PR TITLE
Updating Fakes version in Test Platform

### PR DESCRIPTION
**Pull request by AbhitejJohn**
## Description
Pulling in the latest Fakes package into the Test Platform.

### CODE REVIEW

**Comment by AbhitejJohn** [comment]
I'll validate the generated package on local commandlin scenarios. Do let me know if there are other workflows I should consider too.
/cc: @vritant24

**Review by Evangelink — APPROVED** [review]
LGTM!

@AbhitejJohn You will need to also update https://github.com/microsoft/vstest/blob/main/scripts/verify-nupkgs.ps1#L17

**Review by vritant24 — APPROVED** [review]

**Comment by AbhitejJohn** [comment]
Waiting to use the same version we publish on nuget.

**Comment by Evangelink** [comment]
@AbhitejJohn Build is fixed, I am waiting for your manual check of the NuGet before merging this one out.

**Comment by AbhitejJohn** [comment]
@Evangelink : To reduce the churn in 17.3, I'm planning to merge this in after we snap the branch for 17.4. I'll retry the fakes scenarios as well against the latest changes.

**Comment by Evangelink** [comment]
@AbhitejJohn Do you need some help with this one?

**Comment by AbhitejJohn** [comment]
Abandoned in favor of https://github.com/microsoft/vstest/pull/3912

**Pull request closed without merging**
