### PR TITLE
use log in VSTestLogsTask

### PR DESCRIPTION
**Pull request by adamralph**
## Description

See https://github.com/Microsoft/vstest/pull/1867/files#r240614971

Before this change, messages for build start/completion, and a missing `IsTestProject` property, are printed to the console only, and regardless of the current verbosity level.

After this change, these messages are printed to all configured loggers, with the build start/completion messages only at normal verbosity or higher, and the `IsTestProject` property message at detailed verbosity or higher.

### CODE REVIEW

**Review by singhsarab — APPROVED** [review]

**Comment by adamralph** [comment]
@singhsarab done.

**Comment by adamralph** [comment]
🎉 thanks for the merge!

Do you know which version of the .NET SDK this will be released in? There's no urgency, I'd just like to know when to expect it.

**Comment by adamralph** [comment]
Which version will this be released in?

**Comment by singhsarab** [comment]
@mayankbansal018 is tracking that. Mayank, let's expedite the release.

**Comment by adamralph** [comment]
Any update? I don't necessarily want to expedite the release. I'd just like to know _which version_ it will be released in, so I can set my expectations accordingly.

**Comment by mayankbansal018** [comment]
@adamralph we have already made a release of Testpaltform, please check the [releases](https://github.com/Microsoft/vstest/releases), this is available in latest pre-release.

**Comment by adamralph** [comment]
Thanks @mayankbansal018.

FYI I can't find any mention of this PR in neither https://github.com/Microsoft/vstest/releases nor https://github.com/Microsoft/vstest-docs/blob/master/docs/releases.md

**Comment by singhsarab** [comment]
@adamralph We might have missed added this to the release notes.
It was inserted into the dotnet cli via https://github.com/dotnet/cli/pull/10654

**Comment by adamralph** [comment]
@singhsarab OK, but in any case, this will be released in 16.0.0, correct? Would it be reasonable to put it on the `16.0.0` milestone, so that anyone browsing the PR knows when to expect the change?

**Pull request merged**
