### PR TITLE
Update externals to 16.11

### PR DESCRIPTION
**Pull request by Haplois**
## Description
Update externals to 16.11

Co-authored by: =?UTF-8?q?Jakub=20Jare=C5=A1?= <me@jakubjares.com>

### CODE REVIEW

**Comment by Sanan07** [comment]
Yes, was going to write the same as @nohwnd, we already have update to 17.0 and our real signed pipeline is still not fixed, so no reason to merge it.

**Comment by Haplois** [comment]
I didn't see it sorry :)

**Comment by Haplois** [comment]
@Sanan, should we merge this or #2931?

**Comment by Sanan07** [comment]
We should merge #2931 as @fhnaseer wanted it for Code Coverage. But we should merge it after arcade fix in our signed pipeline.

**Comment by Haplois** [comment]
Let's merge this first than. :) @nohwnd @Sanan07 reviews?

**Comment by Sanan07** [comment]
You can merge it, but there is no sense, cause after some days we will update externals to 17.0 and I assume that there is no change   in externals between 16.10 and 16.11

**Review by Sanan07 — APPROVED** [review]

**Comment by Haplois** [comment]
There is a deprecation message.

**Pull request merged**
