### PR TITLE
Use latest version of dotnet.

### PR DESCRIPTION
**Pull request by harshjain2**
As https://github.com/dotnet/cli/issues/6124 issue is fixed now, reverting the changes to use latest dotnet core package.

### CODE REVIEW

**Comment by harshjain2** [comment]
@dotnet-bot test this.

**Comment by harshjain2** [comment]
@dotnet-bot test this please.

**Comment by harshjain2** [comment]
@dotnet-bot  test this please

**Comment by codito** [comment]
Assigning it to self to investigate the stylecop failures and merge this.

**Review by codito — APPROVED** [review]

**Pull request merged**
