### PR TITLE
Add a way to override test host close timeout by the environment variable VSTEST_CLOSE_TIMEOUT for #1335

### PR DESCRIPTION
**Pull request by NikolayPianikov**

### CODE REVIEW

**Comment by mayankbansal018** [comment]
@NikolayPianikov , thanks for raising this PR, can you also provide some details, as to why this change is needed? Maybe a reference link to some bug

**Comment by ManishJayaswal** [comment]
tagging @mayankbansal018 and I think I was accidently tagged by @NikolayPianikov

**Comment by singhsarab** [comment]
@NikolayPianikov This timeout based on solution does not seem deterministic. On slower machine for an instance, it might not suffice.

I think inproc datacollector is actually the right approach here.

/cc: @pvlakshm @PBoraMSFT

**Comment by NikolayPianikov** [comment]
@singhsarab It is hard coded so far. The suggested PR allows to specify a required timeout. The timeout will be large for our case (TeamCity CI). We are controlling a process tree and can finish processes if it is needed, for example when tests are hanging.

**Review by gighen76 — APPROVED** [review]

**Comment by NikolayPianikov** [comment]
This PR does not change the current behavior by default, it just allows to override hard-coded constant by the environment variable `VSTEST_CLOSE_TIMEOUT `, for instance like as `VSTEST_CONNECTION_TIMEOUT`.

@mayankbansal018, @singhsarab what can I do to make this PR accepted?

**Comment by NikolayPianikov** [comment]
@cltshivash what is the difference between `VSTEST CONNECTION_TIMEOUT` and `VSTEST_CLOSE_TIMEOUT`? Why one timeout should be hard-coded and another does not?

Why the current hard-coded timeout 100 ms is enough from your point fo view and
what if computer is too slow to have enough time to finish all operations (what is actually happening now) in normal way? May be 10 ms or 1000 ms would be better?

`The fix to increase the exit time is not deterministic and will need the customer to change the exit timeout.` What do you mean? By default the timeout is 100 ms as earlier and and here nothing has changed. But we would like to have an ability to set a value for instance like 1 minute, because we are controling the process tree and timeouts as I mentioned in a previous post. 

The inproc data collector scenario supposes that we should change user test settings file to specify our custom collector. It looks like workaround but not as basic usage scenario.

**Comment by cltshivash** [comment]
@NikolayPianikov VSTEST_CONNECTION_TIMEOUT is used in the context of establishing the connection between the different processes involved. (vstest.console.exe, testhost.x86.exe, datacollector.exe). It is kept configurable as we have seen in cases where the profilers are involved, the startup time of the processes can be high. This has been observed on lower config machines used in pipeline pools.

The 100 ms timeout (default) is to provide the testhost process to gracefully exit instead of a termination from the runner. The testhost would have completed all the necessary work and is waiting for the final message to end and we don't expect any other processing to happen at this stage.

**Comment by singhsarab** [comment]
@mayankbansal018 @cltshivash @NikolayPianikov 
I am closing the stale PRs, Should I go ahead close this one?

**Comment by singhsarab** [comment]
Closing this. Please let me know if anyone has concerns.

**Pull request closed without merging**
