### PR TITLE
[Revert] Allow external use of the TRX Logger

### PR DESCRIPTION
**Pull request by singhsarab**
Postponing the change to make TRX public as per discussion.

### CODE REVIEW

**Comment by singhsarab** [comment]
@mayankbansal018 Should we go ahead ?

**Review by smadala — DISMISSED** [review]
> Postponing the change to make TRX public as per discussion.

@singhsarab Can you please elaborate this?

**Comment by dotMorten** [comment]
I'd like to understand the reasoning too (not questioning it, but just want to understand the thinking so I can operate under the same understanding)

**Comment by mayankbansal018** [comment]
@dotMorten , we were internally debating the cost of making TRX logger public, the key thing for us to consider was the fact, that we have to maintain backward compatibility so that the trx do not fail to open in older versions of VS.

Unfortunately the initial change that we took to make it public was not discussed, which caused this issue & we apologize for that.

We are in-fact glad that with your changes folks can generate trx from other test runners as well, two key things I would like to point out.

- TRX is a proprietary format and as a Microsoft policy, we generally maintain back compat, hence schema changes will not be accommodated, which by extension means that we cannot take any change to trx logger, which can cause this to happen.  
- If that constraint is alright, we will go ahead and accept it. If that is not acceptable, we should revert the change.

Given this constraint we were wondering how significant it would be to make trx logger public, w/o allowing changes in schema, which caused the delay. I hope you understand our concerns, & we can proceed safely to make TRX logger as public.

**Comment by dotMorten** [comment]
I don't understand the schema argument. No changes where done that would change the schema, and as minimal as possible amount of members were exposed to just allow other test runners to reuse it to generate a report based on already published objects (ie testresult). No public APIs allow extending the output beyond what it already supports.

Trx might be a MSFT proprietary format, but it's also a defacto standard that so many 3rd party tools already support.

**Comment by mayankbansal018** [comment]
@dotMorten , I agree so far no changes have been made that require changes in schema. 

My argument was not w.r.t to current changes, but from future looking perspective, where if we make TRX logger as public, then a valid ask can come which requires us to alter the schema, but unfortunately we won't be able to take such changes, as it will break the back compat, which we follow as a rule. Again I repeat, I'm talking this from current changes, I hope this clarifies things. 😃

**Comment by dotMorten** [comment]
Not sure I get the argument. You should of course deny any PR/Feature Request that breaks existing customers., including schema changes. That's a given, but IMHO rather irrelevant to this issue.

**Comment by dotMorten** [comment]
I'm assuming there's no problem with adding a v.next schema that customers could opt in to if you one day do want to expand the schema, and if that happens it would just be another overload for this constructor that enables that (or it would be an entirely new logger binary)

**Comment by mayankbansal018** [comment]
@dotMorten I think we can agree to this. I'll close this PR, & we'll wait for you fix the other PR's you raised w.r.t to logger.

**Comment by smadala** [comment]
@mayankbansal018 Thanks for detail explanation. It will be great if the future discussions also happens on github as this is **open source** project.

/cc @singhsarab @PBoraMSFT @cltshivash @codito @smalpani-msft

**Pull request closed without merging**
