### PR TITLE
Build VSIX as part of the solution

### PR DESCRIPTION
**Pull request by sharwell**
This pull request implements the foundations of #798. It addresses all of the blocking items which previously prevented this from moving forward, but leaves several simpler items related to an incomplete localization implementation in [TestPlatform.Localization.targets](https://github.com/Microsoft/vstest/blob/master/scripts/build/TestPlatform.Localization.targets) and the VSIX project not referencing the correct locations for individual project build outputs.

* [x] Work around CPS multi-targeting limitations by explicitly including all source items
  * [x] Use solution references to ensure correct build order, since project references don't work
* [x] Add VSIX project to the solution
  * [x] Fix NuGet restore for the VSSDK
  * [x] Fix debugging properties for the experimental instance
* [ ] Fix solution build producing incorrect output
  * [ ] Fix solution build not localizing files
  * [ ] Fix solution build not placing files in the correct output location (or fix VSIX project to use the actual output location)

Please let me know if any of the remaining work items are not clear so we can unblock other contributors and efficiently as possible. :smile:

### CODE REVIEW

**Comment by codito** [comment]
@sharwell thanks for starting this :+1: We may need to add a task to disable building VSIX from .sln in CLI, the VSSDK build tasks assembly seems to be desktop only. I will play around with this branch and post an update.

**Comment by singhsarab** [comment]
@sharwell 
This seems like a good change to me. What is remaining to complete this one?

**Comment by singhsarab** [comment]
Closing this PR. Please let me know if someone wants to take this up.

**Comment by sharwell** [comment]
@singhsarab As far as I can tell, the remaining items are still the items which are not checked off above

**Pull request closed without merging**
