### PR TITLE
Reimplement the MSBuild VSTestTask task based on ToolTask

### LINKED ISSUE #680: `VSTestTask` only logs to the console
## Description
File logging output contains information about _calling_ the `VSTestTask` but no output from the task itself. This makes it difficult to search the test's output.

## Steps to reproduce
Appears to occur with every ASP.NET repo. For example,
1. `git clone https://github.com/aspnet/HtmlAbstractions.git`
2. `cd HtmlAbstractions\test\Microsoft.Extensions.WebEncoders.Tests`
3. `dotnet restore`
4. `dotnet build`
5. `dotnet test --no-build --framework netcoreapp2.0 /flp:verbosity=diag`
6. `notepad msbuild.log`

## Expected behavior
Same information in the `msbuild.log` file as was shown on the console:
```
Test run for C:\dd\dnx\Universe\.r\HtmlAbstractions\test\Microsoft.Extensions.WebEncoders.Tests\bin\Debug\netcoreapp2.0\Microsoft.Extensions.WebEncoders.Tests.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:00.4636575]   Discovering: Microsoft.Extensions.WebEncoders.Tests
[xUnit.net 00:00:00.5966555]   Discovered:  Microsoft.Extensions.WebEncoders.Tests
[xUnit.net 00:00:00.6391310]   Starting:    Microsoft.Extensions.WebEncoders.Tests
[xUnit.net 00:00:00.8075514]   Finished:    Microsoft.Extensions.WebEncoders.Tests

Total tests: 6. Passed: 6. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 1.9789 Seconds
```

## Actual behavior
Information _around_ the `VSTestTask` call but nothing from the task itself:
```
12:23:02.754     1>Target "VSTest: (TargetId:2)" in file "C:\Users\dougbu\AppData\Local\Microsoft\dotnet\sdk\2.0.0-preview1-005418\Microsoft.TestPlatform.targets" from project "C:\dd\dnx\Universe\.r\HtmlAbstractions\test\Microsoft.Extensions.WebEncoders.Tests\Microsoft.Extensions.WebEncoders.Tests.csproj" (entry point):
                   Task "CallTarget" skipped, due to false condition; ('$(VSTestNoBuild)' != 'true') was evaluated as ('true' != 'true').
                   Using "CallTarget" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
                   Task "CallTarget" (TaskId:2)
                     Task Parameter:Targets=ShowCallOfVSTestTaskWithParameter (TaskId:2)
12:23:02.772     1>Target "ShowCallOfVSTestTaskWithParameter: (TargetId:3)" in file "C:\Users\dougbu\AppData\Local\Microsoft\dotnet\sdk\2.0.0-preview1-005418\Microsoft.TestPlatform.targets" from project "C:\dd\dnx\Universe\.r\HtmlAbstractions\test\Microsoft.Extensions.WebEncoders.Tests\Microsoft.Extensions.WebEncoders.Tests.csproj" (target "VSTest" depends on it):
                   Using "Message" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
                   Task "Message" (TaskId:3)
                     Task Parameter:Text=Calling task Microsoft.TestPlatform.Build.Tasks.VSTestTask with following parameter... (TaskId:3)
                     Task Parameter:Importance=low (TaskId:3)
                     Calling task Microsoft.TestPlatform.Build.Tasks.VSTestTask with following parameter... (TaskId:3)
                   Done executing task "Message". (TaskId:3)
                   Task "Message" (TaskId:4)
                     Task Parameter:Text=TestFileFullPath = C:\dd\dnx\Universe\.r\HtmlAbstractions\test\Microsoft.Extensions.WebEncoders.Tests\bin\Debug\netcoreapp2.0\Microsoft.Extensions.WebEncoders.Tests.dll (TaskId:4)
                     Task Parameter:Importance=low (TaskId:4)
                     TestFileFullPath = C:\dd\dnx\Universe\.r\HtmlAbstractions\test\Microsoft.Extensions.WebEncoders.Tests\bin\Debug\netcoreapp2.0\Microsoft.Extensions.WebEncoders.Tests.dll (TaskId:4)
                   Done executing task "Message". (TaskId:4)
                   Task "Message" (TaskId:5)
                     Task Parameter:Text=VSTestSetting =  (TaskId:5)
                     Task Parameter:Importance=low (TaskId:5)
                     VSTestSetting =  (TaskId:5)
                   Done executing task "Message". (TaskId:5)
                   Task "Message" (TaskId:6)
                     Task Parameter:Text=VSTestTestAdapterPath =  (TaskId:6)
                     Task Parameter:Importance=low (TaskId:6)
                     VSTestTestAdapterPath =  (TaskId:6)
                   Done executing task "Message". (TaskId:6)
                   Task "Message" (TaskId:7)
                     Task Parameter:Text=VSTestFramework = .NETCoreApp,Version=v2.0 (TaskId:7)
                     Task Parameter:Importance=low (TaskId:7)
                     VSTestFramework = .NETCoreApp,Version=v2.0 (TaskId:7)
                   Done executing task "Message". (TaskId:7)
                   Task "Message" (TaskId:8)
                     Task Parameter:Text=VSTestPlatform =  (TaskId:8)
                     Task Parameter:Importance=low (TaskId:8)
                     VSTestPlatform =  (TaskId:8)
                   Done executing task "Message". (TaskId:8)
                   Task "Message" (TaskId:9)
                     Task Parameter:Text=VSTestTestCaseFilter =  (TaskId:9)
                     Task Parameter:Importance=low (TaskId:9)
                     VSTestTestCaseFilter =  (TaskId:9)
                   Done executing task "Message". (TaskId:9)
                   Task "Message" (TaskId:10)
                     Task Parameter:Text=VSTestLogger =  (TaskId:10)
                     Task Parameter:Importance=low (TaskId:10)
                     VSTestLogger =  (TaskId:10)
                   Done executing task "Message". (TaskId:10)
                   Task "Message" (TaskId:11)
                     Task Parameter:Text=VSTestListTests =  (TaskId:11)
                     Task Parameter:Importance=low (TaskId:11)
                     VSTestListTests =  (TaskId:11)
                   Done executing task "Message". (TaskId:11)
                   Task "Message" (TaskId:12)
                     Task Parameter:Text=VSTestDiag =  (TaskId:12)
                     Task Parameter:Importance=low (TaskId:12)
                     VSTestDiag =  (TaskId:12)
                   Done executing task "Message". (TaskId:12)
                   Task "Message" (TaskId:13)
                     Task Parameter:Text=VSTestCLIRunSettings =  (TaskId:13)
                     Task Parameter:Importance=low (TaskId:13)
                     VSTestCLIRunSettings =  (TaskId:13)
                   Done executing task "Message". (TaskId:13)
12:23:02.774     1>Done building target "ShowCallOfVSTestTaskWithParameter" in project "Microsoft.Extensions.WebEncoders.Tests.csproj".: (TargetId:3)
                   Done executing task "CallTarget". (TaskId:2)
                   Using "Microsoft.TestPlatform.Build.Tasks.VSTestTask" task from assembly "C:\Users\dougbu\AppData\Local\Microsoft\dotnet\sdk\2.0.0-preview1-005418\Microsoft.TestPlatform.Build.dll".
                   Task "Microsoft.TestPlatform.Build.Tasks.VSTestTask" (TaskId:14)
                     Task Parameter:TestFileFullPath=C:\dd\dnx\Universe\.r\HtmlAbstractions\test\Microsoft.Extensions.WebEncoders.Tests\bin\Debug\netcoreapp2.0\Microsoft.Extensions.WebEncoders.Tests.dll (TaskId:14)
                     Task Parameter:VSTestFramework=.NETCoreApp,Version=v2.0 (TaskId:14)
                   Done executing task "Microsoft.TestPlatform.Build.Tasks.VSTestTask". (TaskId:14)
12:23:05.787     1>Done building target "VSTest" in project "Microsoft.Extensions.WebEncoders.Tests.csproj".: (TargetId:2)
```

## Environment
Not sure how long this issue has been happening. We don't have MSBuild logs from that far back. The following describes my current environment.

#### `dotnet --info`
```
.NET Command Line Tools (2.0.0-preview1-005418)

Product Information:
 Version:            2.0.0-preview1-005418
 Commit SHA-1 hash:  82c928e1ec

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\dougbu\AppData\Local\Microsoft\dotnet\sdk\2.0.0-preview1-005418\
```

### Operating system, Build version of vstest.console
Logging above mentions `"C:\Users\dougbu\AppData\Local\Microsoft\dotnet\sdk\2.0.0-preview1-005418\Microsoft.TestPlatform.Build.dll".`

### PR DESCRIPTION
**Pull request by mcartoixa**
## Description
The [MSBuild ToolTask class](https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.utilities.tooltask) was designed to help create custom tasks that wraps a command line tool, which is exactly what `VSTestTask` does (it wraps `dotnet.exe exec vstest.console.dll`). Using it allows to delete unneeded code while fixing #680.
The console output lost its colorized output (which was expected) but the task gained the ability to be logged.
A bit of maintenance was performed as well, making use of boolean properties where needed (instead of strings), and of [`ITaskItem`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.framework.itaskitem)s for paths (instead of strings as well). Those changes should be compatible with existing usage though.
Unit tests have been refactored as well along the lines of the new implementation (and are all green, obviously). A real world test has been performed on a project of mine that was affected by #680, on Windows 10 only.
This might need further real world testing.

## Related issue
Fixes #680

### CODE REVIEW

**Comment by mcartoixa** [comment]
I don't seem to be able to execute the failling test on my computer (Visual Studio or CLI) and I fail to see how those are related to my changes. Please advise.

**Comment by nohwnd** [comment]
> The console output lost its colorized output (which was expected) 

Hmm that's a blocker IMHO. We want out colored output even when running from dotnet test.

**Comment by nohwnd** [comment]
Would re-run the pipeline, but it has conflicts. I don't see how the failing test would be related to your changes either.

**Comment by mcartoixa** [comment]
There was no conflict 4 days ago... I'll try and fight my way through git to resolve this (I may learn 1 or 2 things along the way :grin:).
MSBuild always had its own coloring scheme (blue for projects, light gray for command lines, dark gray for command output...) and overriding this would require developing a special case. Note that messages output to the error console show up in red (and obviously fail the task).

**Comment by nohwnd** [comment]
> There was no conflict 4 days ago... I'll try and fight my way through git to resolve this (I may learn 1 or 2 things along the way 😁).

You just need: 
```
# add a remote pointing to the original repo 
# (this is usually called upstream), while your fork is called origin
git add remote upstream  https://github.com/microsoft/vstest.git
# update your forks master to our master
git checkout master
git pull upstream master
# merge your master to your PR branch 
git checkout vstesttask
git merge master
# solve conflicts
... <solve>
git add 
git commit -m"Merge master"
# push to update the PR
git push
```

That said, I don't think this would get merged if we would lose the colors.

**Comment by nohwnd** [comment]
😁  I love the **just** followed by 20 git commands

**Comment by mcartoixa** [comment]
Thanks. I went with a rebase (along the lines of https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request).
You may want to check that I have not messed up too much with your latest commit (I changed some properties to boolean to be consistent with the rest of my PR. You could even use enums for the _DumpType_ arguments...).

As for the color, as I wrote it is inconsistent with MSBuild, but if you insist I'll see what I can do.

**Comment by mcartoixa** [comment]
From what I can gather it is **not possible** to log **and** keep the colored output. You need to choose:
* [ProcessStartInfo.RedirectStandardOutput](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.redirectstandardoutput) (on which [ToolTask](https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.utilities.tooltask) is based) redirects only the _textual_ output.
* There [might be a way](https://stackoverflow.com/a/12574230/8696) to implement a custom console redirection routine using [the ReadConsoleOutput Windows API](https://docs.microsoft.com/en-us/windows/console/readconsoleoutput), but it seems daunting enough for Windows: I cannot imagine myself handling this stuff cross platform.

Please note that in the case of #680 the reporter would be (understandably IMHO) more interested in a searchable log than in a colored output, and that [in my use case](https://github.com/microsoft/vstest/issues/680#issuecomment-517649349) ([MSBuild on AppVeyor](https://www.appveyor.com/docs/build-phase/)) I don't even have a console output: only a log, which is empty.

**Comment by pavelhorak** [comment]
Closing this PR since it would affect expected color output.

**Pull request closed without merging**
