### PR TITLE
LOC CHECKIN | Microsoft/vstest - 15.0-rtm | 20170131

### PR DESCRIPTION
**Pull request by v-zbsail**

### CODE REVIEW

**Comment by codito** [comment]
@Faizan2304 can you please merge and validate?

@sbaid @piotrpMSFT @srivatsn we may need to take this in the next insertion for RTM.

**Review by codito — APPROVED** [review]

**Comment by codito** [comment]
There are several changes due to `<note></note>` changed to `<note/>`. @Faizan2304 does it require fix in xlftool?

**Comment by Faizan2304** [comment]
@codito : the change related to <note></note> doesn't require fix in xlftool.exe.

**Comment by Faizan2304** [comment]
@v-zbsail: Thank you very much.

**Pull request merged**
