### PR TITLE
Add platform abstraction for OS name and architecture.

### PR DESCRIPTION
**Pull request by codito**
Related #820 #679

### CODE REVIEW

**Comment by codito** [comment]
This is a quick spike. I will add tests in next commit to this PR.

**Comment by codito** [comment]
@dotnet-bot test this please

**Review by smadala — APPROVED** [review]

**Comment by codito** [comment]
@dotnet-bot test this please

**Comment by DavidKarlas** [comment]
I assume this will be merged soon?

**Comment by codito** [comment]
I am running a few end to end tests, will get it in today.

**Pull request merged**
