### PR TITLE
Add a zero-width space after test name in HTML results

### PR DESCRIPTION
**Pull request by RikkiGibson**
This PR adjusts the HTML results generation to make it easier to highlight the name of the test with a double-click. I've attached a GIF which shows the existing behavior, and demonstrates a JavaScript snippet which achieves a similar result as this PR.

After the change, it's much easier to double-click, copy the name of the test, and ctrl+F for it in some other place, such as the file where the test is declared.

The JavaScript snippet is not part of the actual change, but included here for reference:
```js
document.querySelectorAll(".leaf-division div:first-child span:nth-of-type(2)").forEach(elem => elem.innerHTML += "&#8203;")
```

zero-width-space-after-test-name

### CODE REVIEW

**Review by Haplois — APPROVED** [review]

**Comment by Evangelink** [comment]
@RikkiGibson Would you be able to merge/rebase main, we fixed an issue that's affecting your PR.

**Comment by RikkiGibson** [comment]
Have merged in the latest main. Thanks!

**Comment by RikkiGibson** [comment]
Thanks very much @Haplois @Evangelink!

**Comment by Evangelink** [comment]
Thank you for your contribution!

**Pull request merged**
