### PR TITLE
Ngen testhost and testhost.x86...

### PR DESCRIPTION
**Pull request by KevinH-MS**
## Description
I noticed in profiling test execution for Live Unit Testing that we're spending a relatively large amount of time jit'ing for each test run (because the number of tests run as part of an individual execution request is relatively small).

## Related issue
https://github.com/dotnet/testimpact/issues/2397

### CODE REVIEW

**Comment by KevinH-MS** [comment]
FYI @AbhitejJohn @codito @sudiptadmsft

**Comment by singhsarab** [comment]
@KevinH-MS Can you please share the improvement numbers?

**Comment by KevinH-MS** [comment]
@singhsarab timing the scenario in the linked LUT issue under the profiler, the savings is almost exactly 100ms (I measured 99-103ms).

That said, it seems the overall scenario has regressed since the last time I measured it (from ~900ms to ~1.7s) 🤕, so I'll need to do some more digging for other improvements as well.  Originally, this looked like it would be a 10% improvement.  Now, it looks like only a 5% improvement against the current state of 15.6 preview 2.

**Review by AbhitejJohn — APPROVED** [review]

**Review by smadala — COMMENTED** [review]
From [doc](https://docs.microsoft.com/en-us/dotnet/framework/tools/ngen-exe-native-image-generator) 
>/Debug: Generate native images that can be used under a debugger.
/Profile: Generate native images that can be used under a profiler.

How can this change impact the debugging (both test code and testhost code) and profile test scenario?

From [doc](https://docs.microsoft.com/en-us/visualstudio/extensibility/ngen-support)
> In order to "ngen" an assembly, the VSIX must be installed "per-instance per-machine" 

How this impact the VSIX installation behavior?

Please test the BVT scenarios explicitly installing VSIX with these changes and upgrade VSIX scenario(testhost native image should update in cache).

Both testhost and vstest.console share common dependencies(CommunicationUtilities, CrossPlatEngine, etc.. ), Will we get the benefit in vstest.console too?

**Comment by KevinH-MS** [comment]
> How can this change impact the debugging (both test code and testhost code) and profile test scenario?

Neither should be impacted (assuming that you're using the VS debugger).  The VS debugger will load the IL image by default when attached.  "/Profile" is for partial ngen profiling (i.e. "OptProf"), not profiling tests.

> How this impact the VSIX installation behavior?

I do not anticipate that it will.  This is the standard VSIX v3 authoring metadata used by all Willow components that are packaged as a VSIX.  For example, Roslyn:  https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/Setup/VisualStudioSetup.csproj#L33

> Please test the BVT scenarios explicitly installing VSIX with these changes and upgrade VSIX scenario(testhost native image should update in cache).

Sure--how do I queue a BVT run? (or where are the BVT tests?)

> Both testhost and vstest.console share common dependencies(CommunicationUtilities, CrossPlatEngine, etc.. ), Will we get the benefit in vstest.console too?

I can't say for certain, but my guess is "no", because they aren't listed as ngen roots.  If you wanted to add those too, it would be trivial though (but it's less likely to matter as much, because vstest.console scenarios are less likely to be dominated by startup time).  If there are cases where you launch vstest.console to run, say, 1 test, then it would be worth ngen'ing.

**Comment by mayankbansal018** [comment]
Hi Kevin, 
Few questions:

What would be the layout upon installing this vsix? From ngen [doc](https://docs.microsoft.com/en-us/dotnet/framework/tools/ngen-exe-native-image-generator#Anchor_3) the assemblies inside "IDE\Extension\TestPlatform" will not be ngen'ed but ngen'ed assemblies placed in GAC "C:\Windows\assembly\NativeImages_v4.0.30319_64. 

vstest.console launches testhost via Path. If ngen'ed assemblies are placed in GAC and not is same folder, will CLR launch testhost from GAC? If it does not launches from GAC will it still load ngen'ed assemblies from GAC?

How will this impact SxS scenario where user has multiple VS2017 on their machines? Our assembly version for all dll's is constant across VS2017 which is 15.0.0.0 Upon inserting new vsix will the older ngen'ed assemblies be replaced?

**Comment by KevinH-MS** [comment]
@mayankbansal018 

The layout upon install will not change.  The CLR loader will still probe for the assembly in the same path, but upon load, it will opportunistically use the ngen image if it can.  I honestly don't know all the details of the implementation, but it goes something like "if the IL assembly matches the ngen image and the loader context is one of the ngen roots of this assembly, then use the ngen image" (otherwise, the loader falls back to loading the IL image).  "Matches" is defined by a number of criteria, which I believe include the file size, file timestamp and assembly MVID.  There is some additional info at:  https://microsoft.sharepoint.com/teams/DD_DDInfo/DDELib/DDELib_Wiki/RPS%20Walkthrough%20-%20NGen%20issues.aspx, but beyond that, you'd have to follow up with someone from the CLR team or go look at the loader sources if you want to understand all the details of how it works.

I'm not trying to be dismissive, and I wish I could explain with greater detail and clarity, but my point is that all the other Willow components that ngen assemblies (which is, in fact, most of them) use this same mechanism, and anecdotally, ngen/the CLR "does the right thing". 😄 

Also note: the ngen cache is not the GAC (they are largely orthogonal except I believe there are some special rules about when the ngen image is loaded if the assembly ***is*** in the GAC).  This change does not GAC any assemblies though.

This will also not affect SxS (in the same way that it does not affect SxS for any of the other assemblies in the VS install), because ngen uses a stronger notion of assembly identity than the assembly name/version/public key (again, I don't know the exact details, but if you look under C:\Windows\assembly\NativeImages_v4.0.30319_32 on your machine, you'll probably notice there are multiple versions of, say, "Microsoft.Build.ni.dll").

**Comment by AbhitejJohn** [comment]
@KevinH-MS : On the following:

>how do I queue a BVT run? (or where are the BVT tests?)

Probably we can just run `test.cmd -p smoke` and `test.cmd -p acceptance`. You might want to tweak the script to ensure it picks up vstest.console and testhost.exe from the installed vsix and not from the build output. That should help us figure out if anything is broken. We do have `Assembly.LoadFrom` in code which the ngen docs frown upon but the tests should be able to catch those issues.

**Comment by codito** [comment]
> You might want to tweak the script to ensure it picks up vstest.console and testhost.exe from the installed vsix and not from the build output.

Might be easier if we replace the `artifacts\Debug\win7-xyz` directory contents with those from the VSIX directory (Extensions\TestPlatform).

**Comment by mayankbansal018** [comment]
@KevinH-MS , did you get a chance to validate CLR Profiling scenario(CodeCoverage / Fakes) we discussed for ngen images?

**Comment by KevinH-MS** [comment]
Hey @mayankbansal018 , sorry, the profiler was broken on my machine for a while and then I got side-tracked by other things...

I tried it just now, and 'Profile Test' still works after ngen'ing testhost and testhost.x86:
image

**Comment by KevinH-MS** [comment]
Analyze Code Coverage doesn't work on my machine (with or without ngen).  Not sure how to diagnose further, but below is my diagnostic log from VS.  Is there a command line scenario I could try?

```
[2/2/2018 4:44:41 PM Informational] ------ Load Playlist started ------
[2/2/2018 4:44:41 PM Informational] ========== Load Playlist finished (0:00:00) ==========
[2/2/2018 4:44:58 PM Informational] ------ Run test started ------
[2/2/2018 4:45:09 PM Informational] ========== Run test finished: 1 run (0:00:10.0599478) ==========
[2/2/2018 4:46:17 PM Diagnostic] Discovering tests in C:\Users\kevinh\Source\Repos\UnitTestProject4\UnitTestProject4\UnitTest1.cs
[2/2/2018 4:46:17 PM Diagnostic] GetTestCount UnitTest1 Time = 3.0182
[2/2/2018 4:46:19 PM Diagnostic] About to Enqueue operation 'RunSelectedOperation', hashcode:30809022 
[2/2/2018 4:46:19 PM Diagnostic] Enqueue operation 'RunSelectedOperation', hashcode:30809022 
[2/2/2018 4:46:19 PM Diagnostic] Operation left in the the queue: 1
[2/2/2018 4:46:19 PM Diagnostic] 	'RunSelectedOperation', hashcode:30809022
[2/2/2018 4:46:19 PM Diagnostic] 

[2/2/2018 4:46:19 PM Diagnostic] Processing Queue .....
[2/2/2018 4:46:19 PM Diagnostic] Operation Dequeue : 'RunSelectedOperation'
[2/2/2018 4:46:19 PM Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=OperationSetStarted, operationInProgress=False
[2/2/2018 4:46:19 PM Diagnostic] TestDiscoveryStats.OperationStateChanged State=OperationSetStarted, InProgress=False
[2/2/2018 4:46:19 PM Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=ChangeDetectionStarting, operationInProgress=True
[2/2/2018 4:46:19 PM Diagnostic] TestDiscoveryStats.OperationStateChanged State=ChangeDetectionStarting, InProgress=False
[2/2/2018 4:46:19 PM Diagnostic] We programmatically start the build in TestWindowHost.UpdateContainer... 
[2/2/2018 4:46:25 PM Diagnostic] After we await the build that programmatically started in TestWindowHost.UpdateContainer... 
[2/2/2018 4:46:25 PM Diagnostic] TestContainer update (build) complete : 6 sec
[2/2/2018 4:46:25 PM Diagnostic] Adding the Project in Project Map for Guid abc8ac8c-079e-4f9c-8d8f-234da8e6cad6
[2/2/2018 4:46:25 PM Diagnostic] test container discoverer executor://vsprojectoutputcontainerdiscoverer/v1, discovered 1 containers
[2/2/2018 4:46:25 PM Diagnostic] Containers from 'Microsoft.VisualStudio.TestWindow.VsAdapters.VsProjectOutputContainerDiscoverer' :
[2/2/2018 4:46:25 PM Diagnostic] 	C:\Users\kevinh\Source\Repos\UnitTestProject4\UnitTestProject4\bin\Debug\UnitTestProject4.dll:executor://vsprojectoutputcontainerdiscoverer/v1
[2/2/2018 4:46:25 PM Diagnostic] test container discoverer executor://testexplorerservicecontainerdiscoverer/v1, discovered 0 containers
[2/2/2018 4:46:25 PM Diagnostic] No containers found from 'Microsoft.VisualStudio.TestWindow.Extensibility.TestExplorerServiceContainerDiscoverer' :
[2/2/2018 4:46:25 PM Diagnostic] test container discoverer executor://93a465e5-dcd0-4df0-b4db-94a42ed9bbab/v1, discovered 0 containers
[2/2/2018 4:46:25 PM Diagnostic] No containers found from 'Microsoft.VisualStudio.CMake.Project.TestExplorer.BoostTestContainerDiscoverer' :
[2/2/2018 4:46:25 PM Diagnostic] test container discoverer executor://f049acae-b5a8-4e11-8186-7dd1478b69b4/v1, discovered 0 containers
[2/2/2018 4:46:25 PM Diagnostic] No containers found from 'Microsoft.VisualStudio.CMake.Project.TestExplorer.BoostVsTestContainerDiscoverer' :
[2/2/2018 4:46:25 PM Diagnostic] test container discoverer executor://cmakectest/1.0, discovered 0 containers
[2/2/2018 4:46:25 PM Diagnostic] No containers found from 'Microsoft.VisualStudio.CMake.Project.TestExplorer.CTestContainerDiscoverer' :
[2/2/2018 4:46:25 PM Diagnostic] test container discoverer executor://527e0cfc-7d85-4331-b9f2-a8868486ffbe/v1, discovered 0 containers
[2/2/2018 4:46:25 PM Diagnostic] No containers found from 'Microsoft.VisualStudio.CMake.Project.TestExplorer.GoogleVsContainerDiscoverer' :
[2/2/2018 4:46:25 PM Diagnostic] test container discoverer executor://3bd7de78-9b87-4843-a29f-19175bc54285/v1, discovered 0 containers
[2/2/2018 4:46:25 PM Diagnostic] No containers found from 'Microsoft.VisualStudio.CMake.Project.TestExplorer.GoogleVsInBoxContainerDiscoverer' :
[2/2/2018 4:46:25 PM Diagnostic] test container discoverer executor://db3301db-4425-47a5-a6e1-d0cced8d750c/v1, discovered 0 containers
[2/2/2018 4:46:25 PM Diagnostic] No containers found from 'Microsoft.VisualStudio.CMake.Project.TestExplorer.GoogleGitHubContainerDiscoverer' :
[2/2/2018 4:46:25 PM Diagnostic] test container discoverer executor://cpsprojectoutputtestcontainerdiscoverer/v2, discovered 0 containers
[2/2/2018 4:46:25 PM Diagnostic] No containers found from 'Microsoft.VisualStudio.TestWindow.Extensions.CPSTestContainerDiscoverer' :
[2/2/2018 4:46:25 PM Diagnostic] test container discoverer executor://orderedtestadapter/v1, discovered 0 containers
[2/2/2018 4:46:25 PM Diagnostic] No containers found from 'Microsoft.VisualStudio.MSTest.TestWindow.OrderedTestContainerDiscoverer' :
[2/2/2018 4:46:25 PM Diagnostic] test container discoverer executor://generictestadapter/v1, discovered 0 containers
[2/2/2018 4:46:25 PM Diagnostic] No containers found from 'Microsoft.VisualStudio.MSTest.TestWindow.GenericTestContainerDiscoverer' :
[2/2/2018 4:46:25 PM Diagnostic] test container discoverer executor://webtestadapter/v1, discovered 0 containers
[2/2/2018 4:46:25 PM Diagnostic] No containers found from 'Microsoft.VisualStudio.MSTest.TestWindow.WebTestContainerDiscoverer' :
[2/2/2018 4:46:25 PM Diagnostic] DiscoveryOperation<RunSelectedOperation> FinishedChangedCotainers, changed container count is 1
[2/2/2018 4:46:25 PM Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=ChangeDetectionFinished, operationInProgress=False
[2/2/2018 4:46:25 PM Diagnostic] TestDiscoveryStats.OperationStateChanged State=ChangeDetectionFinished, InProgress=False
[2/2/2018 4:46:25 PM Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=TestExecutionStarting, operationInProgress=False
[2/2/2018 4:46:25 PM Diagnostic] TestDiscoveryStats.OperationStateChanged State=TestExecutionStarting, InProgress=False
[2/2/2018 4:46:25 PM Informational] ------ Run test started ------
[2/2/2018 4:46:25 PM Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=TestExecutionStarted, operationInProgress=False
[2/2/2018 4:46:25 PM Diagnostic] TestDiscoveryStats.OperationStateChanged State=TestExecutionStarted, InProgress=False
[2/2/2018 4:46:25 PM Diagnostic] RunSettings Content:
<RunSettings>
  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="Code Coverage" uri="datacollector://Microsoft/CodeCoverage/2.0" assemblyQualifiedName="Microsoft.VisualStudio.Coverage.DynamicCoverageDataCollector, Microsoft.VisualStudio.TraceCollector">
        <Configuration>
          <CoverageFileName>kevinh_KEVINH-TEST 2018-02-02 16_46_25.coverage</CoverageFileName>
          <CodeCoverage>
            <ModulePaths>
              <Exclude>
                <ModulePath>.*CPPUnitTestFramework.*</ModulePath>
              </Exclude>
              <Include>
                <ModulePath>.*\\UnitTestProject4\.dll</ModulePath>
              </Include>
            </ModulePaths>
            <UseVerifiableInstrumentation>True</UseVerifiableInstrumentation>
            <AllowLowIntegrityProcesses>True</AllowLowIntegrityProcesses>
            <CollectFromChildProcesses>True</CollectFromChildProcesses>
            <CollectAspDotNet>False</CollectAspDotNet>
            <SymbolSearchPaths />
            <Functions>
              <Exclude>
                <Function>^std::.*</Function>
                <Function>^ATL::.*</Function>
                <Function>.*::__GetTestMethodInfo.*</Function>
                <Function>.*__CxxPureMSILEntry.*</Function>
                <Function>^Microsoft::VisualStudio::CppCodeCoverageFramework::.*</Function>
                <Function>^Microsoft::VisualStudio::CppUnitTestFramework::.*</Function>
                <Function>.*::YOU_CAN_ONLY_DESIGNATE_ONE_.*</Function>
                <Function>^__.*</Function>
                <Function>.*::__.*</Function>
              </Exclude>
            </Functions>
            <Attributes>
              <Exclude>
                <Attribute>^System.Diagnostics.DebuggerHiddenAttribute$</Attribute>
                <Attribute>^System.Diagnostics.DebuggerNonUserCodeAttribute$</Attribute>
                <Attribute>^System.Runtime.CompilerServices.CompilerGeneratedAttribute$</Attribute>
                <Attribute>^System.CodeDom.Compiler.GeneratedCodeAttribute$</Attribute>
                <Attribute>^System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute$</Attribute>
              </Exclude>
            </Attributes>
            <Sources>
              <Exclude>
                <Source>.*\\atlmfc\\.*</Source>
                <Source>.*\\vctools\\.*</Source>
                <Source>.*\\public\\sdk\\.*</Source>
                <Source>.*\\externalapis\\.*</Source>
                <Source>.*\\microsoft sdks\\.*</Source>
                <Source>.*\\vc\\include\\.*</Source>
                <Source>.*\\msclr\\.*</Source>
                <Source>.*\\ucrt\\.*</Source>
              </Exclude>
            </Sources>
            <CompanyNames>
              <Exclude>
                <CompanyName>.*microsoft.*</CompanyName>
              </Exclude>
            </CompanyNames>
            <PublicKeyTokens>
              <Exclude>
                <PublicKeyToken>^B77A5C561934E089$</PublicKeyToken>
                <PublicKeyToken>^B03F5F7F11D50A3A$</PublicKeyToken>
                <PublicKeyToken>^31BF3856AD364E35$</PublicKeyToken>
                <PublicKeyToken>^89845DCD8080CC91$</PublicKeyToken>
                <PublicKeyToken>^71E9BCE111E9429C$</PublicKeyToken>
                <PublicKeyToken>^8F50407C4E9E73B6$</PublicKeyToken>
                <PublicKeyToken>^E361AF139669C375$</PublicKeyToken>
              </Exclude>
            </PublicKeyTokens>
          </CodeCoverage>
        </Configuration>
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
  <RunConfiguration>
    <ResultsDirectory>C:\Users\kevinh\Source\Repos\UnitTestProject4\TestResults</ResultsDirectory>
    <SolutionDirectory>C:\Users\kevinh\Source\Repos\UnitTestProject4\</SolutionDirectory>
    <TargetPlatform>X86</TargetPlatform>
    <TargetFrameworkVersion>Framework45</TargetFrameworkVersion>
  </RunConfiguration>
  <GoogleTestAdapterSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <SolutionSettings>
      <Settings />
    </SolutionSettings>
    <ProjectSettings />
  </GoogleTestAdapterSettings>
</RunSettings>
[2/2/2018 4:46:31 PM Diagnostic] Active tests:1 TestResults:0
[2/2/2018 4:46:31 PM Diagnostic] TestMethod1

[2/2/2018 4:46:31 PM Diagnostic] GetTestCount UnitTest1 Time = 0.9945
[2/2/2018 4:46:32 PM Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=OperationSetFinished, operationInProgress=False
[2/2/2018 4:46:32 PM Diagnostic] TestDiscoveryStats.OperationStateChanged State=OperationSetFinished, InProgress=False
[2/2/2018 4:46:32 PM Diagnostic] Active tests:0 TestResults:1
[2/2/2018 4:46:32 PM Diagnostic] ***    Run finished using 'InMemoryUnitTestWriter' ***
[2/2/2018 4:46:32 PM Diagnostic]        Intended run TestCases : 1, received TestResults : 1;   NotRun : 0, Passed : 0, Skipped : 0, Failed : 1
[2/2/2018 4:46:32 PM Diagnostic] Report Reader.GetTestsInRange: Total time:0:00:00.0009997
[2/2/2018 4:46:32 PM Diagnostic]            UnitTest1: 1
[2/2/2018 4:46:32 PM Diagnostic]        Total Reader.GetTestsInRange called:1
[2/2/2018 4:46:32 PM Diagnostic]        Total Reader.GetTestsInRange: Average time: 0:00:00.0009997
[2/2/2018 4:46:32 PM Diagnostic] 

Report Reader.GetTestCount: Total time:0:00:00.0009945
[2/2/2018 4:46:32 PM Diagnostic]            UnitTest1: 1
[2/2/2018 4:46:32 PM Diagnostic]        Reader.GetTestCount called:1
[2/2/2018 4:46:32 PM Diagnostic]        Total Reader.GetTestCount: Average time: 0:00:00.0009945
[2/2/2018 4:46:32 PM Diagnostic] 

Report StorageChangedNotification.NotifyChangeViews: Total time:0:00:00.0010017
[2/2/2018 4:46:32 PM Diagnostic]        Notification requested: 3, actual performed: 3
[2/2/2018 4:46:32 PM Diagnostic]        Report StorageChangedNotification.NotifyChangeViews: Average time: 0:00:00.0003339
[2/2/2018 4:46:32 PM Informational] ========== Run test finished: 1 run (0:00:06.6212015) ==========
[2/2/2018 4:46:32 PM Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=TestExecutionFinished, operationInProgress=False
[2/2/2018 4:46:32 PM Diagnostic] TestDiscoveryStats.OperationStateChanged State=TestExecutionFinished, InProgress=False
[2/2/2018 4:46:32 PM Diagnostic] GetTestCount UnitTest1 Time = 2.0006
[2/2/2018 4:46:32 PM Diagnostic] GetTestCount UnitTest1 Time = 0.9915
```

**Comment by KevinH-MS** [comment]
Analyze Code Coverage magically started working when I installed the latest 15.6 preview 4 bits...

image

(it appears to work fine with testhost ngen'ed)

@mayankbansal018 anything else I should try?

**Comment by mayankbansal018** [comment]
@KevinH-MS , this is good enough.

**Review by mayankbansal018 — APPROVED** [review]

**Comment by KevinH-MS** [comment]
@mayankbansal018 @singhsarab I've resolved the conflicts with this PR.  Anything else that needs to be done to merge?

**Comment by KevinH-MS** [comment]
retest Windows_NT please

**Comment by KevinH-MS** [comment]
retest this please

**Comment by KevinH-MS** [comment]
I'm seeing this:
image
@mayankbansal018 @singhsarab can someone with write access help me merge?

**Comment by KevinH-MS** [comment]
Thanks!

**Pull request merged**
