### PR TITLE
Added new exception handling

### PR DESCRIPTION
**Pull request by Sanan07**
## Description
Added new exception handling to handle exception while trying to create "TestResults" folder

### CODE REVIEW

**Comment by nohwnd** [comment]
Do you still have it built? Could you post some screenshots? :)

**Comment by Sanan07** [comment]
> Do you still have it built? Could you post some screenshots? :)

Screenshot of what?

**Comment by nohwnd** [comment]
The cmd, and what it outputs when it gets the access denied. :)

**Comment by Sanan07** [comment]
> The cmd, and what it outputs when it gets the access denied. :)
If you reproduce the project in bug description you should see this message :
tempsnip
For all other test projects, you should see this one : 
build_1

**Review by cvpoienaru — APPROVED** [review]

**Comment by nohwnd** [comment]
Cherry picked 50b5b33 into rel/16.7

**Comment by nohwnd** [comment]
Which part of the product are these changes affecting? Is it testhost, or vstest console? Just trying to figure out if updating the insertion into VS is needed, or if updating test.SDK nuget is needed to get this change.

**Comment by Sanan07** [comment]
I assume both updating are needed. It affects data collector part and baseRunTest class, so as I understand they are test host and data collector parts. We updated Test.SDK nuget to be able to work correctly on .net core project.

**Pull request merged**
