### PR TITLE
Sync for binarywriter writes

### PR DESCRIPTION
**Pull request by singhsarab**
Add the lock for writes using the binary writer as it is not thread safe

### CODE REVIEW

**Comment by mayankbansal018** [comment]
@dotnet-bot test this

**Comment by mayankbansal018** [comment]
@dotnet-bot test this please

**Comment by singhsarab** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Review by mayankbansal018 — APPROVED** [review]

**Pull request merged**
