### PR TITLE
Retire VsixCreator

### PR DESCRIPTION
**Pull request by Faizan2304**

### CODE REVIEW

**Review by AbhitejJohn — APPROVED** [review]

**Review by codito — APPROVED** [review]
Please check if Microsoft.Internal.* packages are already referred elsewhere.

**Comment by Faizan2304** [comment]
> Please check if Microsoft.Internal.* packages are already referred elsewhere
 
No other project has package reference of Microsoft.Internal.TestPlatform.Extensions other than external.csproj

**Comment by Faizan2304** [comment]
@dotnet-bot test Windows / Debug Build  please

**Comment by Faizan2304** [comment]
@dotnet-bot test Windows / Debug Build please

**Pull request merged**
