### PR TITLE
Restructure acceptance tests 

### PR DESCRIPTION
**Pull request by smadala**
## Description
- Restructure the acceptance tests to handle MSTest V2 data source changes.

### CODE REVIEW

**Review by acesiddhu — APPROVED** [review]
:shipit:

**Review by acesiddhu — APPROVED** [review]

**Comment by smadala** [comment]
@dotnet-bot please test.

**Comment by smadala** [comment]
@dotnet-bot please test Windows_NT / Release Build.

**Comment by smadala** [comment]
@dotnet-bot Please test Windows_NT / Release Build.

**Comment by smadala** [comment]
@dotnet-bot test Windows_NT / Release Build.

**Pull request merged**
