### PR TITLE
Mitigate the usage of JsonConvert.DefaultSettings in user code

### LINKED ISSUE #1360: Tests never finish when JsonConvert DefaultSettings changed
## Description
Hopefully I am reporting this in the correct place, sorry if not!
Running in either VS2017 or using `dotnet test`, the runner hangs indefinitely if the `JsonConvert.DefaultSettings` have been set as below:
```
JsonConvert.DefaultSettings = () => new JsonSerializerSettings
{
    ContractResolver = new DefaultContractResolver
    {
        NamingStrategy = new SnakeCaseNamingStrategy()
    }
};
```
I have tested this using MSTest, Nunit and Xunit and the same issue seems to happen across the board, which leads me to believe its the vstest runner itself.

## Steps to reproduce
[XUnitTestProject1.zip](https://github.com/Microsoft/vstest/files/1603270/XUnitTestProject1.zip)
Above is a sample project with 2 tests. One which hangs and one which doesn't. 

## Expected behavior
For the tests to finish running

## Actual behavior
Tests never finish running. I have to go and end the dotnet process manually.

## Diagnostic logs
[logs.zip](https://github.com/Microsoft/vstest/files/1603288/logs.zip)

## Environment
Windows 10, .net core 2.0

[AB#1866683](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1866683)

### PR DESCRIPTION
**Pull request by Applesauce314**
## Description

!1881 removed direct usage of `JsonConvert.DefaultSettings` but the serialization was still sensitive to user code changing this value due to the use of `JsonConvert.Serialize` and `JsonConvert.Deserialize` during _fast_ serialization/deserialization

## Related issue

Fixes #1360 

- [x] I have ensured that there is a previously discussed and approved issue. (#1360 is closed but it did solicit help fixing the issue)

### CODE REVIEW

**Comment by Applesauce314** [comment]
note that the contributing guideline ask that there be an issue discussed and approved before a pull request is created, #1360 is closed, but the last comment is a solicitation for a contribution to fix the problem, if you need an open issue, let me know and I can create one.

**Comment by Applesauce314** [comment]
@microsoft-github-policy-service agree company="General Dynamics"

**Comment by Applesauce314** [comment]
is there anything I need to do on that test failure? it appears that that particular test often fails with that error.

**Comment by nohwnd** [comment]
Nice, the tests finally passed, I will have to have a proper look at that code. Everything is relying on this.  

It would also be nice to have an acceptance test that helps us not regress this. Would you be able to add one?

**Comment by Applesauce314** [comment]
> Nice, the tests finally passed, I will have to have a proper look at that code. Everything is relying on this.
> 
> It would also be nice to have an acceptance test that helps us not regress this. Would you be able to add one?

I would like to, however my system is not longer able to build successfully (we updated vs recently, maybe that), so not sure when i can get to it, don't have time to debug.

**Comment by Applesauce314** [comment]
i figured out how codespaces worked, so no more using the CI to check my tests (sorry about that).
i added a test, but have not yet verified that it fails in a branch prior to my build

**Comment by Applesauce314** [comment]
I verified that the tests I added fail in main prior to my changes.

**Review by nohwnd — APPROVED** [review]

**Comment by nohwnd** [comment]
I think it is safe to merge, thank you!

**Pull request merged**
