### PR TITLE
Removing UWP runtime provider insertion,

### PR DESCRIPTION
**Pull request by mayankbansal018**
UWP team will insert it directly from devdiv

### CODE REVIEW

**Comment by mayankbansal018** [comment]
@dotnet-bot test Windows_NT / Release Build

**Comment by mayankbansal018** [comment]
@dotnet-bot test Windows_NT / Release Build please

**Comment by smadala** [comment]
@dotnet-bot please test Windows_NT / Release Build

**Comment by smadala** [comment]
@dotnet-bot please test this

**Comment by smadala** [comment]
@dotnet-bot please test this.

**Comment by mayankbansal018** [comment]
@dotnet-bot test Windows_NT / Debug Build please

**Comment by mayankbansal018** [comment]
@dotnet-bot test this please

**Comment by mayankbansal018** [comment]
@dotnet-bot test Windows_NT / Debug Build

**Comment by mayankbansal018** [comment]
@dotnet-bot tests Windows_NT / Debug Build

**Comment by mayankbansal018** [comment]
@dotnet-bot test Windows_NT / Debug Build

**Review by singhsarab — APPROVED** [review]

**Review by smadala — APPROVED** [review]

**Pull request merged**
