### PR TITLE
Nuspec for TRX Logger

### PR DESCRIPTION
**Pull request by dotMorten**
## Description
Follow-up in issue #1791 and expose TRX Logger as a nuget package

## Related issue
#1791

### CODE REVIEW

**Comment by dotMorten** [comment]
I'm not sure why this PR didn't built on Windows. The OOM error reported shouldn't be caused by this PR I think.

**Comment by dotMorten** [comment]
Not sure this PR still makes sense, due to PR #1806 (albeit it might make sense later, pending clarification whey the change needed for this PR was reverted)

**Comment by mayankbansal018** [comment]
@dotMorten , any progress on this?

**Comment by dotMorten** [comment]
@mayankbansal018 progress on what? Afaik this is ready to go and haven't received any PR feedback to indicate anything else need to happen

**Comment by mayankbansal018** [comment]
@dotMorten , as you can see the build has failed. I was hoping you could see why it failed, & re-trigger it. I'll take a look at the PR.

**Comment by dotMorten** [comment]
I can't see the build details now (404), but it was the compilation throwing Out-of-memory, and only on Windows. I don't see how that's related? Seems like a build server issue, and builds ok locally.

**Comment by mayankbansal018** [comment]
@dotnet-bot test this please

**Comment by mayankbansal018** [comment]
@dotMorten , We have fixed the CI, a change in required from your end in file https://github.com/Microsoft/vstest/blob/d9a0690801b872bd68ed0a91e9c3f8206992c45e/scripts/verify-nupkgs.ps1#L15 .For each nuget we verify that whatever number of files are inserted, are actually present

**Comment by dotMorten** [comment]
Got it! I'll fix

**Review by mayankbansal018 — APPROVED** [review]

**Review by mayankbansal018 — APPROVED** [review]

**Pull request merged**
