### PR TITLE
Updating externals to 17.0 (with tests)

### PR DESCRIPTION
**Pull request by nohwnd**
## Description
Update external dependencies to 17.0 with ignored tests (from #2931) enabled. 

## Related issue
Fix #2931

### CODE REVIEW

**Comment by nohwnd** [comment]
@Haplois #2931 with tests enabled.

**Comment by nohwnd** [comment]
@Haplois  why did you close this?

**Comment by Haplois** [comment]
@nohwnd - the other one merged and this PR's checks was failing; would you prefer it to be open?

**Comment by nohwnd** [comment]
Yeah, I'd like to fix those tests.

**Comment by Sanan07** [comment]
That interop work is not finished yet, return to "ignoring tests" state.

**Comment by Sanan07** [comment]
No need to this PR, as we already updated externals and finished CUIT interop work.

**Comment by Haplois** [comment]
@Sanan07 - Shouldn't we enable those tests?

**Comment by Sanan07** [comment]
@Haplois Yes, I will enable them in my new PR with removal of generic tests

**Pull request closed without merging**
